# Generated by Django 5.2.7 on 2025-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before video appears'),
        ),
    ]
