# Generated by Django 5.2.7 on 2025-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('computer_engineering', 'Computer Engineering'), ('computer_science', 'Computer Science'), ('electrical_engineering', 'Electrical Engineering'), ('it', 'Information Technology')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='General description of the field')),
                ('exam_info', models.TextField(help_text='Information about the entrance exam')),
                ('subjects', models.TextField(help_text='Main subjects covered in the exam')),
                ('career_opportunities', models.TextField(blank=True, help_text='Career opportunities after graduation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
