# Generated by Django 5.2.7 on 2025-11-15 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='notes/')),
                ('field', models.CharField(blank=True, help_text='Field of study (optional)', max_length=100)),
                ('approved', models.BooleanField(default=False, help_text='Admin must approve before note appears')),
                ('is_paid', models.BooleanField(default=False, help_text='Is this a paid note? (Teachers only)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in currency units', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='notes.note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('student', 'note')},
            },
        ),
    ]
