# Generated by Django 5.2.7 on 2025-12-02 14:25

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to=notes.models.note_upload_path),
        ),
    ]
